# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  head_pan:
    has_velocity_limits: true
    max_velocity: 1.4
    has_acceleration_limits: false
    max_acceleration: 0
  head_tilt:
    has_velocity_limits: true
    max_velocity: 1.4
    has_acceleration_limits: false
    max_acceleration: 0
  l_elbow:
    has_velocity_limits: true
    max_velocity: 2.5
    has_acceleration_limits: false
    max_acceleration: 0
  l_f0_j0:
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: false
    max_acceleration: 0
  l_f1_j0:
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: false
    max_acceleration: 0
  l_shoulder_pitch:
    has_velocity_limits: true
    max_velocity: 2.5
    has_acceleration_limits: false
    max_acceleration: 0
  l_shoulder_roll:
    has_velocity_limits: true
    max_velocity: 2.5
    has_acceleration_limits: false
    max_acceleration: 0
  l_shoulder_yaw:
    has_velocity_limits: true
    max_velocity: 2.5
    has_acceleration_limits: false
    max_acceleration: 0
  l_wrist_roll:
    has_velocity_limits: true
    max_velocity: 1.4
    has_acceleration_limits: false
    max_acceleration: 0
  l_wrist_yaw1:
    has_velocity_limits: true
    max_velocity: 1.4
    has_acceleration_limits: false
    max_acceleration: 0
  l_wrist_yaw2:
    has_velocity_limits: true
    max_velocity: 1.4
    has_acceleration_limits: false
    max_acceleration: 0
  r_elbow:
    has_velocity_limits: true
    max_velocity: 2.5
    has_acceleration_limits: false
    max_acceleration: 0
  r_f0_j0:
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: false
    max_acceleration: 0
  r_f1_j0:
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: false
    max_acceleration: 0
  r_shoulder_pitch:
    has_velocity_limits: true
    max_velocity: 2.5
    has_acceleration_limits: false
    max_acceleration: 0
  r_shoulder_roll:
    has_velocity_limits: true
    max_velocity: 2.5
    has_acceleration_limits: false
    max_acceleration: 0
  r_shoulder_yaw:
    has_velocity_limits: true
    max_velocity: 2.5
    has_acceleration_limits: false
    max_acceleration: 0
  r_wrist_roll:
    has_velocity_limits: true
    max_velocity: 1.4
    has_acceleration_limits: false
    max_acceleration: 0
  r_wrist_yaw1:
    has_velocity_limits: true
    max_velocity: 1.4
    has_acceleration_limits: false
    max_acceleration: 0
  r_wrist_yaw2:
    has_velocity_limits: true
    max_velocity: 1.4
    has_acceleration_limits: false
    max_acceleration: 0
  waist_lidar:
    has_velocity_limits: true
    max_velocity: 2.5
    has_acceleration_limits: false
    max_acceleration: 0
  waist_pan:
    has_velocity_limits: true
    max_velocity: 2.5
    has_acceleration_limits: false
    max_acceleration: 0
  waist_tilt:
    has_velocity_limits: true
    max_velocity: 2.5
    has_acceleration_limits: false
    max_acceleration: 0
